CREATE DATABASE dbtest;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
   id UUID NOT NULL UNIQUE DEFAULT uuid_generate_v4(),
   name VARCHAR NOT NULL,
   code VARCHAR NOT NULL UNIQUE,
   dateOfBirth DATE NOT NULL,
   photo VARCHAR NOT NULL
);
